server:
  port: 8081


spring:
  application:
    name: product_service
  datasource:
    url: jdbc:h2:file:./data/productdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-products
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/